version: '3.1'

services:
  huy_db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - 5436:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data